// SIDE: CLIENT
// ^, JEI Ingredient Removals affects Client Only

package post.main.mod.jei

import static com.nomiceu.nomilabs.groovy.GroovyHelpers.MaterialHelpers.hideMaterial

import com.nomiceu.nomilabs.util.LabsModeHelper
import gregtech.api.unification.material.Material

/* Unobtainable Ore Removals */
mods.jei.ingredient.with {
    var removeOres = { Material mat, Integer... metas ->
        for (var meta : metas) {
            hide(item("gregtech:ore_${mat}_0", meta))
        }
    }

    var (NORMAL, NETHER, END) = [0, 1, 2]

    removeOres(material('nomilabs:draconium'), NORMAL, NETHER)
    removeOres(material('nomilabs:osmiridium_8020'), NETHER, END)
    removeOres(material('nomilabs:iridosmine_8020'), NETHER, END)
    removeOres(material('nomilabs:kaemanite'), NETHER, END)
    removeOres(material('nomilabs:fluorite'), NETHER, END)
    removeOres(material('nomilabs:laurite'), NORMAL, END)
    removeOres(material('nomilabs:cuprorhodsite'), NORMAL, END)
    removeOres(material('aluminium'), NETHER)
    removeOres(material('beryllium'), END)
    removeOres(material('cobalt'), NORMAL, NETHER, END)
    removeOres(material('iron'), NETHER, END)
    removeOres(material('lead'), NETHER, END)
    removeOres(material('lithium'), NETHER)
    removeOres(material('molybdenum'), END)
    removeOres(material('neodymium'), END)
    removeOres(material('nickel'), NETHER, END)
    removeOres(material('palladium'), NETHER)
    removeOres(material('platinum'), NETHER)
    removeOres(material('plutonium'), NORMAL, NETHER, END)
    removeOres(material('silver'), END)
    removeOres(material('sulfur'), END)
    removeOres(material('thorium'), END)
    removeOres(material('tin'), END)
    removeOres(material('naquadah'), NETHER, END)
    removeOres(material('certus_quartz'), END)
    removeOres(material('almandine'), END)
    removeOres(material('asbestos'), NETHER, END)
    removeOres(material('banded_iron'), END)
    removeOres(material('blue_topaz'), NORMAL, END)
    removeOres(material('brown_limonite'), END)
    removeOres(material('calcite'), NETHER, END)
    removeOres(material('cassiterite_sand'), NETHER, END)
    removeOres(material('chalcopyrite'), NETHER, END)
    removeOres(material('chromite'), NORMAL, NETHER)
    removeOres(material('cinnabar'), END)
    removeOres(material('coal'), NETHER, END)
    removeOres(material('cobaltite'), END)
    removeOres(material('diamond'), NETHER, END)
    removeOres(material('emerald'), END)
    removeOres(material('galena'), NETHER, END)
    removeOres(material('garnierite'), NETHER, END)
    removeOres(material('green_sapphire'), NETHER, END)
    removeOres(material('grossular'), END)
    removeOres(material('bauxite'), NETHER)
    removeOres(material('lazurite'), NETHER, END)
    removeOres(material('magnesite'), NETHER, END)
    removeOres(material('magnetite'), NETHER)
    removeOres(material('molybdenite'), END)
    removeOres(material('powellite'), END)
    removeOres(material('pyrite'), END)
    removeOres(material('pyrolusite'), END)
    removeOres(material('pyrope'), NETHER, END)
    removeOres(material('rock_salt'), NETHER, END)
    removeOres(material('ruby'), END)
    removeOres(material('salt'), NETHER, END)
    removeOres(material('saltpeter'), END)
    removeOres(material('sapphire'), END)
    removeOres(material('sodalite'), NETHER, END)
    removeOres(material('spessartine'), NETHER, END)
    removeOres(material('stibnite'), END)
    removeOres(material('tetrahedrite'), END)
    removeOres(material('topaz'), END)
    removeOres(material('uraninite'), NETHER)
    removeOres(material('wulfenite'), END)
    removeOres(material('yellow_limonite'), END)
    removeOres(material('nether_quartz'), END)
    removeOres(material('quartzite'), END)
    removeOres(material('graphite'), NETHER, END)
    removeOres(material('bornite'), NORMAL)
    removeOres(material('chalcocite'), NORMAL, END)
    removeOres(material('realgar'), NETHER, END)
    removeOres(material('bastnasite'), END)
    removeOres(material('pentlandite'), END)
    removeOres(material('spodumene'), NETHER, END)
    removeOres(material('lepidolite'), END)
    removeOres(material('glauconite_sand'), NETHER, END)
    removeOres(material('malachite'), NETHER, END)
    removeOres(material('mica'), NETHER, END)
    removeOres(material('barite'), END)
    removeOres(material('alunite'), NORMAL, END)
    removeOres(material('talc'), NETHER, END)
    removeOres(material('soapstone'), NETHER, END)
    removeOres(material('kyanite'), NETHER, END)
    removeOres(material('oilsands'), NETHER)
    removeOres(material('olivine'), NETHER, END)
    removeOres(material('opal'), NETHER, END)
    removeOres(material('amethyst'), NETHER, END)
    removeOres(material('lapis'), NETHER, END)
    removeOres(material('apatite'), NETHER, END)
    removeOres(material('tricalcium_phosphate'), NETHER, END)
    removeOres(material('garnet_red'), NETHER, END)
    removeOres(material('garnet_yellow'), NETHER, END)
    removeOres(material('pollucite'), NETHER, END)
    removeOres(material('bentonite'), NETHER, END)
    removeOres(material('fullers_earth'), NETHER, END)
    removeOres(material('pitchblende'), NETHER)
    removeOres(material('monazite'), END)
    removeOres(material('gypsum'), NETHER, END)
    removeOres(material('zeolite'), NETHER, END)
    removeOres(material('redstone'), END)
    removeOres(material('electrotine'), END)
    removeOres(material('diatomite'), END)
    removeOres(material('granitic_mineral_sand'), NETHER, END)
    removeOres(material('garnet_sand'), NETHER, END)
    removeOres(material('basaltic_mineral_sand'), NETHER, END)

    hide(metaitem('dustImpureCobalt'))
    hide(metaitem('dustPureCobalt'))
    hide(metaitem('crushedCobalt'))
    hide(metaitem('crushedPurifiedCobalt'))
    hide(metaitem('crushedCentrifugedCobalt'))
    hide(metaitem('dustImpurePlutonium'))
    hide(metaitem('dustPurePlutonium'))
    hide(metaitem('crushedPlutonium'))
    hide(metaitem('crushedPurifiedPlutonium'))
    hide(metaitem('crushedCentrifugedPlutonium'))

    if (LabsModeHelper.normal) {
        removeOres(material('cooperite'), NETHER)
        removeOres(material('tantalite'), END)
        removeOres(material('pentlandite'), NETHER)
    }

    if (LabsModeHelper.expert) {
        removeOres(material('snowchestite'), NETHER, END)
        removeOres(material('darmstadtite'), NORMAL, NETHER)
        removeOres(material('dulysite'), NORMAL, NETHER)
        removeOres(material('lithium'), NORMAL)
        removeOres(material('neodymium'), NORMAL)
        removeOres(material('platinum'), NORMAL)
        removeOres(material('sulfur'), NORMAL)
        removeOres(material('thorium'), NORMAL)
        removeOres(material('naquadah'), NORMAL)
        removeOres(material('cooperite'), NORMAL)
        removeOres(material('powellite'), NORMAL)
        removeOres(material('saltpeter'), NORMAL)
        removeOres(material('topaz'), NORMAL)
        removeOres(material('barite'), NORMAL)
        removeOres(material('electrotine'), NORMAL)

        hide(metaitem('dustImpureNaquadah'))
        hide(metaitem('dustPureNaquadah'))
        hide(metaitem('crushedNaquadah'))
        hide(metaitem('crushedPurifiedNaquadah'))
        hide(metaitem('crushedCentrifugedNaquadah'))
    }

    hideMaterial(material('trona'))
}
