name: Bug Report
description: Crashes or unintended behaviors arising from Nomi-CEu's mods, configurations, or custom scripts
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! 

        Note: If you need general tech support for things like server configuration, or general game support (how to I make this?), Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.
  - type: dropdown
    id: version
    attributes:
      label: Nomi-CEu Version
      description: The version of Nomi-CEu you were using when this bug was encountered. If you do not know what this is, check the title of your instance window. If you do not see your version here, please update to the newest version of the pack, which currently is 1.6, or the newest alpha/beta, which currently is 1.6.1-alpha-1. 
      options:
        - "1.6.1-alpha-1"
        - "1.6"
        - "1.5.2"
        - "1.5.1"
        - "1.5"
        - "1.4.3"
        - "1.4.2"
        - "1.4.1a"
        - "1.4"
        
    validations:
      required: true
  - type: textarea
    id: changed
    attributes:
      label: Configurations or Mods Changed
      description: Any changed configs, and removed or added mods. Make sure to also include the version of any mods you have added. If you have not changed any configurations, and not removed or added any mods, please leave this field blank.
      placeholder: |
        Example:
        Changed Loliasm Config: B:onDemandAnimatedTextures to false.
        Added AE2 Fluid Crafting Rework: Version 2.4.18-r.
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "How you were playing on the world. Typical answers include: Singleplayer, Open to LAN, Forge Server, Sponge Server, or Mohist Server."
      placeholder: "Example: Singleplayer"
    validations:
      required: true
  - type: dropdown
    id: world
    attributes:
      label: New Worlds
      description: Does this bug occur on a newly generated world?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: dropdown
    id: cross-mod
    attributes:
      label: Cross-Mod Interaction
      description: Does this bug occur because of another mod installed alongside GregTech CEu?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen. Attach screenshots here as necessary.
      placeholder: "Example: Expected to produce X by consuming Y."
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Actual Behavior
      description: What happened despite your expectations. Attach screenshots here as necessary.
      placeholder: "Example: Produced one X but Y was not consumed."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely caused by X because..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report.
