name: Feature Request
description: Suggest an idea, including mod additions or addon scripts, for Nomi CEu.
labels: enhancement
body:
  - type: markdown
    attributes:
      value: "Note: balancing ideas should use this template, but only for changes. However, if its a problem, not a change, like `X material always runs out`, please use the `Bug Report` Template."
  - type: dropdown
    id: version
    attributes:
      label: Nomi CEu Version
      description: The version of Nomi CEu you were using when this bug was encountered. If you do not know what this is, check the title of your instance window. If you do not see your version here, please update to the newest version of the pack, which currently is 1.6, or the newest alpha/beta, which currently is 1.6.1-alpha-1. 
      options:
        - "1.6.1-alpha-1"
        - "1.6"
        - "1.5.2"
        - "1.5.1"
        - "1.5"
        - "1.4.3"
        - "1.4.2"
        - "1.4.1a"
        - "1.4"
    validations:
        required: true
  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: If the feature you wish to change is related to a problem, please desscribe it. Leave this field blank if it is not related to a problem.
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Your Solution
      description: Describe the solution you would like to have happen.
      placeholder: "Example: If I could..."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely achieveable by doing X because..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this feature request.
