name: Feature Request
description: Suggest an idea, including mod additions or addon scripts, for Nomi CEu.
labels: enhancement
body:
  - type: markdown
    attributes:
      value: "Note: balancing ideas should use this template, but only for changes. However, if its a problem, not a change, like `X material always runs out`, please use the `Bug Report` Template."
  - type: dropdown
    id: version
    attributes:
      label: Nomi CEu Version
      description: The version of Nomi CEu you are using as the basis for this feature request. If you do not know what it is, check the title of your instance window. If you do not see your version here, please update to the newest version of the pack, which currently is 1.6, or the newest alpha/beta, which currently is 1.6.1-alpha-1. 
      options:
        - "1.6.1-alpha-1"
        - "1.6"
        - "1.5.2"
        - "1.5.1"
        - "1.5"
        - "1.4.3"
        - "1.4.2"
        - "1.4.1a"
        - "1.4"
    validations:
        required: true
  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: If the feature you wish to change is related to a problem, please desscribe it. Leave this field blank if it is not related to a problem.
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Your Solution
      description: Describe the solution you would like to have happen.
      placeholder: "Example: If I could..."
    validations:
      required: true
  - type: textarea
    id: work
    attributes:
      label: How Will Your Solution Work
      description: |
        Describe how the solution will fix the problem, or add to the pack. 
        If you are suggesting a mod, please describe what the mod does, and how it will add to the pack.
      placeholder: "Example: If X was done, than Y will get a use, and..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives You've Considered"
      description: "What alternatives have you considered that might help solve the problem? If you aren't sure, or this is not related to a problem, please leave this field blank."
      placeholder: "Example: Otherwise, we can also do Z..."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Add any other context or screenshots about the feature request here. If you are suggesting a mod, please also add a link to the mod's CurseForge page."
      placeholder: "Example: This main motive for this idea is because X..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this feature request.
