name: "Build Pack"

on:
  workflow_call:
    inputs:
      tag:
        description: Tag to Checkout.
        required: false
        type: string
      changelog_url:
        description: Where to download the Changelog file from.
        required: false
        type: string
      changelog_cf_url:
        description: Where to download the CF Changelog file from.
        required: false
        type: string
      changelog_branch:
        description: Branch to download changelog files from.
        required: false
        type: string
      compare_tag:
        description: Tag to compare, to make Changelog.
        required: false
        type: string
  workflow_dispatch:
    inputs:
        tag:
          description: Tag to Checkout.
          required: false
          type: string
        changelog_url:
          description: Where to download the Changelog file from.
          required: false
          type: string
        changelog_cf_url:
          description: Where to download the CF Changelog file from.
          required: false
          type: string
        changelog_branch:
          description: Branch to download changelog files from.
          required: false
          type: string
        compare_tag:
          description: Tag to compare, to make Changelog.
          required: false
          type: string
      
jobs:
  build:
    name: Build Pack (${{ inputs.tag }})
    runs-on: ubuntu-latest
    env:
      GITHUB_TAG: ${{ inputs.tag }}

    steps:
      - name: Checkout Ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}

      - name: Restore Cached Files
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.npm
            ./.cache
            ./tools/node_modules
          key: ${{ runner.os }}-bunny-${{ hashFiles('**/.cache', '**/package-lock.json', '**/manifest.json') }}
          restore-keys: ${{ runner.os }}-bunny-

      - name: Setup NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      - name: Setup NPM Packages
        working-directory: ./tools
        run: npm ci

      - name: Check Environmental Variables
        working-directory: ./tools
        run: npx gulp check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
          CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
          CFCORE_API_TOKEN: ${{ secrets.CFCORE_API_TOKEN }}

      - name: Build Pack
        working-directory: ./tools
        run: npx gulp buildAll
        env:
          CFCORE_API_TOKEN: ${{ secrets.CFCORE_API_TOKEN }}
          CHANGELOG_BRANCH: ${{ inputs.changelog_branch }}
          CHANGELOG_URL: ${{ inputs.changelog_url }}
          CHANGELOG_CF_URL: ${{ inputs.changelog_cf_url }}
          COMPARE_TAG: ${{ inputs.compare_tag }}

      - name: Zip Pack
        working-directory: ./tools
        run: npx gulp zipAll

      - name: Upload Built Zips
        uses: actions/upload-artifact@v3
        with:
          name: Built Pack
          path: |
            ./build/*.zip
            ./build/*.md
          if-no-files-found: error
