name: "[CALLABLE] Deploy to GitHub Releases & CurseForge"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to Checkout and Release.
        required: true
        type: string
      release_type:
        description: The Release Type.
        required: true
        type: choice
        default: 'Release'
        options:
          - 'Release'
          - 'Beta Release'
          - 'Alpha Release'
      changelog_url:
        description: Where to download the Changelog File from. See CHANGELOG.md for more information.
        required: false
        type: string
      changelog_cf_url:
        description: Where to download the CF Changelog File from. See CHANGELOG.md for more information.
        required: false
        type: string
      changelog_branch:
        description: Branch to download changelog Files from. See CHANGELOG.md for more information.
        required: false
        type: string

jobs:
  build:
    name: Build Pack (${{ github.event.inputs.tag }})
    uses: ./.github/workflows/build-pack.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      changelog_url: ${{ github.event.inputs.changelog_url }}
      changelog_cf_url: ${{ github.event.inputs.changelog_cf_url }}
      changelog_branch: ${{ github.event.inputs.changelog_branch }}
    secrets: inherit

  deployGH:
    name: Deploy to GitHub Releases (${{ github.event.inputs.tag }})
    needs: build
    uses: ./.github/workflows/deploygh.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit

