name: "[NOT CALLABLE] Push Build Pack"
on:
  push:
    branches:
      - main
      - test_buildscript*

# if a second commit is pushed quickly after the first, cancel the first one's build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    # Only allow runs from commits to Nomi-CEu Branches
    if: "${{ github.repository_owner == 'IntegerLimit' }}"
    name: Push Build Pack
    uses: ./.github/workflows/buildpack.yml
    with:
      separate_upload: true
    secrets: inherit

