name: Test Commit Syntax

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test_buildscript*

jobs:
  testCommits:
    if: "${{ github.repository_owner == 'Nomi-CEu' }}"
    name: Test Commits
    uses: ./.github/workflows/createchangelog.yml
    with:
      release_type: "Cutting Edge Build"
      test: true
    secrets: inherit
    permissions:
      contents: write
