name: "[NOT CALLABLE] Test Build Pack"
on:
  push:
    branches:
      - main
      - test_buildscript*

  pull_request:

# if a second commit is pushed quickly after the first, cancel the first one's build
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true
  
jobs:
  build:
    # Only allow runs from commits to Nomi-CEu Branches, and pull requests from Nomi-CEu base repo
    if: "${{ github.repository_owner == 'IntegerLimit' && ( !github.event.pull_request || github.event.pull_request.head.repo.owner.name == 'IntegerLimit' ) }}"
    name: Build Pack
    uses: ./.github/workflows/buildpack.yml
    with:
      separate_upload: true
    secrets: inherit

