# This workflow updates the main json files, and the en_us.lang, after a Quest Book change.
name: Update Quest Book Jsons and Lang

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - qb-lang-revamp # Temp, for testing
    paths:
      - "overrides/config/betterquesting/saved_quests/NormalQuestsDev.json" # Normal QB Developer Json
      - "overrides/config/betterquesting/saved_quests/ExpertQuestsDev.json" # Expert QB Developer Json

jobs:
  updateQB:
    name: Update Quest Book Jsons and Lang (${{ github.event.inputs.tag }})
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: "Restore cached files"
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.npm
            ./.cache
            ./tools/node_modules
          key: ${{ runner.os }}-bunny-${{ hashFiles('**/.cache', '**/package-lock.json', '**/manifest.json') }}
          restore-keys: ${{ runner.os }}-bunny-

      - name: "Setup NodeJS v16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true

      - name: "Download NPM packages"
        working-directory: ./tools
        run: npm ci

      - name: "Transform QB"
        working-directory: ./tools
        run: npx gulp transformQB

      - name: "Commit and push QB Changes"
        run: |
          # Define all paths to push
          PATHS="./overrides/resources/questbook/lang/en_us.lang
          ./overrides/config/betterquesting/saved_quests/ExpertQuests.json
          ./overrides/config-overrides/normal/betterquesting/DefaultQuests.json
          ./overrides/config-overrides/expert/betterquesting/DefaultQuests.json"
            
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull origin main
          git commit $PATHS --message "Update Quest Book Jsons and Lang" || echo "No QB Changes Detected. This may be intended, or an error."; exit 1
          git push origin main
